services:
  api:
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./examples:/app/examples
    environment:
      UVICORN_WORKERS: "1"
      UVICORN_RELOAD: "true"

  db:
    ports:
      - "5432:5432"
