"""allow failed compilations in the rule cache

Revision ID: 0f17743c5967
Revises: c81eaaf76ee6
Create Date: 2026-10-02 15:14:22.879132

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f17743c5967'
down_revision: Union[str, Sequence[str], None] = 'c81eaaf76ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compiled_rule', 'rule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Cached failures have no rule and can't survive NOT NULL.
    op.execute("DELETE FROM compiled_rule WHERE rule IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compiled_rule', 'rule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
