"""create initial tables

Revision ID: 52e2b6e8b9a9
Revises: 
Create Date: 2026-10-01 23:41:25.716353

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e2b6e8b9a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before the chunk.embedding column can be created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('authority', sa.String(length=300), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'parsing', 'indexing', 'cataloguing', 'ready', 'failed')", name=op.f('ck_tariff_document_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariff_document')),
    sa.UniqueConstraint('checksum', name=op.f('uq_tariff_document_checksum'))
    )
    op.create_table('calculation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('port_key', sa.String(length=100), nullable=True),
    sa.Column('vessel_call', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'partial', 'failed')", name=op.f('ck_calculation_status')),
    sa.ForeignKeyConstraint(['document_id'], ['tariff_document.id'], name=op.f('fk_calculation_document_id_tariff_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation'))
    )
    op.create_index('ix_calculation_created', 'calculation', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_calculation_port_created', 'calculation', ['port_key', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_calculation_status', 'calculation', ['status'], unique=False)
    op.create_table('charge_catalogue_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('charge_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('section_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payer', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payer IN ('vessel', 'cargo', 'other')", name=op.f('ck_charge_catalogue_entry_payer')),
    sa.CheckConstraint("trigger IN ('per_call', 'per_service', 'per_period', 'on_request', 'licence_or_permit')", name=op.f('ck_charge_catalogue_entry_trigger')),
    sa.ForeignKeyConstraint(['document_id'], ['tariff_document.id'], name=op.f('fk_charge_catalogue_entry_document_id_tariff_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charge_catalogue_entry')),
    sa.UniqueConstraint('document_id', 'charge_id', name=op.f('uq_charge_catalogue_entry_document_id_charge_id'))
    )
    op.create_table('compiled_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('port_key', sa.String(length=100), nullable=False),
    sa.Column('charge_id', sa.String(length=100), nullable=False),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_schema_version', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('critic_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tariff_document.id'], name=op.f('fk_compiled_rule_document_id_tariff_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compiled_rule')),
    sa.UniqueConstraint('document_id', 'port_key', 'charge_id', 'rule_schema_version', 'prompt_version', name=op.f('uq_compiled_rule_cache_key'))
    )
    op.create_index('ix_compiled_rule_lookup', 'compiled_rule', ['document_id', 'port_key'], unique=False)
    op.create_table('document_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ref', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='body', nullable=False),
    sa.CheckConstraint("kind IN ('body', 'definitions', 'contents')", name=op.f('ck_document_section_kind')),
    sa.ForeignKeyConstraint(['document_id'], ['tariff_document.id'], name=op.f('fk_document_section_document_id_tariff_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_section.id'], name=op.f('fk_document_section_parent_id_document_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_section')),
    sa.UniqueConstraint('document_id', 'ordinal', name=op.f('uq_document_section_document_id_ordinal'))
    )
    op.create_index('ix_document_section_document_ref', 'document_section', ['document_id', 'ref'], unique=False)
    op.create_index('ix_document_section_parent', 'document_section', ['parent_id'], unique=False)
    op.create_table('agent_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.UUID(), nullable=False),
    sa.Column('charge_id', sa.String(length=100), nullable=True),
    sa.Column('node', sa.String(length=50), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], name=op.f('fk_agent_step_calculation_id_calculation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_step'))
    )
    op.create_index('ix_agent_step_calculation', 'agent_step', ['calculation_id', 'id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('printed_page', sa.String(length=20), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.CheckConstraint("kind IN ('text', 'table', 'definition')", name=op.f('ck_chunk_kind')),
    sa.ForeignKeyConstraint(['document_id'], ['tariff_document.id'], name=op.f('fk_chunk_document_id_tariff_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_section.id'], name=op.f('fk_chunk_section_id_document_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk'))
    )
    op.create_index('ix_chunk_document_section', 'chunk', ['document_id', 'section_id'], unique=False)
    op.create_index('ix_chunk_embedding_hnsw', 'chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunk_tsv', 'chunk', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_tsv', table_name='chunk', postgresql_using='gin')
    op.drop_index('ix_chunk_embedding_hnsw', table_name='chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunk_document_section', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index('ix_agent_step_calculation', table_name='agent_step')
    op.drop_table('agent_step')
    op.drop_index('ix_document_section_parent', table_name='document_section')
    op.drop_index('ix_document_section_document_ref', table_name='document_section')
    op.drop_table('document_section')
    op.drop_index('ix_compiled_rule_lookup', table_name='compiled_rule')
    op.drop_table('compiled_rule')
    op.drop_table('charge_catalogue_entry')
    op.drop_index('ix_calculation_status', table_name='calculation')
    op.drop_index('ix_calculation_port_created', table_name='calculation')
    op.drop_index('ix_calculation_created', table_name='calculation')
    op.drop_table('calculation')
    op.drop_table('tariff_document')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
